export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_REJECTED = 'FETCH_PRODUCTS_REJECTED';
export const FETCH_PRODUCTS_FULFILLED = 'FETCH_PRODUCTS_FULFILLED';

export const SET_PRODUCT = 'SET_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_REJECTED = 'FETCH_PRODUCT_REJECTED';
export const FETCH_PRODUCT_FULFILLED = 'FETCH_PRODUCT_FULFILLED';

export const SET_HEADER = 'SET_HEADER';
export const CLEAR_HEADER = 'CLEAR_HEADER';
